name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/kuronami69/MemKernel/main/kernel/setup.sh" | bash -s M

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: gcc/12 # Make sure to specify the correct compiler version here
        defconfig: vayu_defconfig   # Make sure to specify the correct defconfig here
        image: Image.gz-dtb

    - name: List Output Directory
      run: |
        echo "Listing contents of the output directory:"
        ls -R ./out/drivers/memkernel/

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: kernel-module
        path: |
          ${{ steps.build.outputs.outfile }} # Adjust this if necessary based on your build outputs
          ./out/drivers/memkernel/memkernel.ko
